report_columns = {
    # Basic Report
    'Stock': "Ativo",
    'Starting Capital': "Capital Inicial",
    'Trade Cost': "Custo Operacional",
    'Total Trade Cost': "Custo Operacional Total",
    'Ending Capital': "Capital Final",
    'Net Profit Value': "Lucro (R$)",
    'Net Profit %': "Lucro (%)",
    'Start Date': "Data Inicial",
    'End Date': "Data Final",
    'Annualized Profit %': "Lucro Anualizado (%)",
    'Annual Volatility %': "Volatilidade Anualizada (%)",
    # General Trades
    'Number of Trades': "Número de trades",
    'Active Trade': "Trade Ativo",
    'Average Return Value': "Média de retorno (R$)",
    'Average Return %': "Média de retorno (%)",
    'Gain/Loss Ratio': "Razão Ganho/Perda",
    'Payoff Ratio/Factor': "Payoff",
    'Mathematical Expectation': "Expectativa Matemática",
    'Max Duration': "Duração Máxima (dias)",
    'Average Duration': "Duração Média (dias)",
    'Min Duration': "Duração Mínima (dias)",
    # Gain trades
    'Number of Gain Trades': "Trades Vencedores",
    'Win Rate %': "Taxa de Acerto (%)",
    'Max Profit Value': "Lucro Máximo (R$)",
    'Average Profit Value': "Lucro Médio (R$)",
    'Min Profit Value': "Lucro Mínimo (R$)",
    'Max Profit %': "Lucro Máximo (%)",
    'Average Profit %': "Lucro Médio (R$)",
    'Min Profit %': "Lucro Mínimo (%)",
    'Max Win Trade Duration': "Duração Máxima (dias)",
    'Average Win Trade Duration': "Duração Média (dias)",
    'Min Win Trade Duration': "Duração Mínima (dias)",
    'Max Consecutive Wins': "Máximo de Ganhos Consecutivos",
    'Average Consecutive Wins': "Média de Ganhos Consecutivos",
    # Loss trades
    'Number of Loss Trades': "Trades Perdedores",
    'Loss Rate %': "Taxa de Perda (%)",
    'Max Loss Value': "Perda Máxima (R$)",
    'Average Loss Value': "Perda Média (R$)",
    'Min Loss Value': "Perda Mínima (R$)",
    'Max Loss %': "Perda Máxima (%)",
    'Average Loss %': "Perda Média (%)",
    'Min Loss %': "Perda Mínima (%)",
    'Max Loss Trade Duration': "Duração Máxima (dias)",
    'Average Loss Trade Duration': "Duração Média (dias)",
    'Min Loss Trade Duration': "Duração Mínima (dias)",
    'Max Consecutive Losses': "Máximo de Perdas Consecutivos",
    'Average Consecutive Losses': "Média de Perdas Consecutivas",
    # Drawdown
    'Maximum Drawdown Value': "Valor Máximo de Drawdown (R$)",
    'Maximum Drawdown %': "Valor Máximo de Drawdown (%)",
    'Maximum Drawdown Date': "Data de Drawdown Máximo",
    'Maximum Drawdown Duration': "Maior Duração de Drawdown (dias)",
    'Average Peak Drawdown %': "Porcentagem Média de Drawdown (%)",
    'Average Drawdown Duration': "Duração Média de Drawdown (dias)",
    'Recovery Factor': "Fator de Recuperação"
}