setups_description = {
    'ff_fd': {'condition': 'Bandas de Bollinger 20 periodos.',
              'entry': 'rompimento imediato da máxima do primeiro candle que fechou dentro da Banda de Bollinger.',
              'target': 'banda central da Bollinger, média móvel de 20.',
              'stop': 'perda da mínima do candle gatilho.'},
    'inside_bar': {'condition': '',
                   'entry': 'rompimento da máxima do inside bar (cancelada se houver perda da mínima do inside bar).',
                   'target': '2x amplitude do inside bar.',
                   'stop': 'perda da mínima do candle (inside bar) gatilho.'},
    'max_min': {'condition': '',
                'entry': 'mínima dos 2 últimos candles',
                'target': '',
                'stop': 'máxima dos 2 últimos candles.'},
    'pfr': {'condition': 'candle PFR (mínima menor que as 2 últimas e fechamento maior que candle anterior).',
            'entry': 'rompimento da máxima do candle PFR (cancelada se houver perda da mínima do candle PFR).',
            'target': '2x amplitude do candle PFR.',
            'stop': 'perda da mínima do candle (PFR) gatilho.'},
    'rsi_2': {'condition': 'RSI 2 períodos.',
              'entry': 'fechamento do candle com RSI menor que 25.',
              'target': 'máxima dos 2 últimos candles.',
              'stop': 'após 7 candles.'},
    'setup_123': {'condition': '123 (candle 1 com mínima maior que candle 2 cuja mínima é menor que candle 3).',
                  'entry': 'rompimento da máxima do terceiro candle (cancelada se houver perda da menor mínima do 123).',
                  'target': '2x amplitude do 123 (da maior máxima até menor mínima).',
                  'stop': 'perda da menor mínima do 123.'},
    'setup_9_1': {'condition': 'média móvel exponencial 9 períodos.',
                  'entry': 'rompimento da máxima do candle que virar a mme9 para cima (cancelada se mme9 virar para baixo).',
                  'target': 'perda da mínima do candle que virar a mme9 para baixo (cancelado se mme9 virar para cima).',
                  'stop': 'perda da mínima do candle gatilho.'}
}